name: ekyc
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.5
  go_router: ^14.1.4
  intl: ^0.19.0
  url_launcher: ^6.1.12
  google_fonts: ^4.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.3
  flutter_svg: ^1.0.3
  equatable: ^2.0.5
  collection: ^1.18.0
  popover: ^0.3.0
  path_provider: ^2.1.3
  http: ^0.13.6
  image_picker: ^0.8.6+1
  camera: ^0.10.0+4
  provider: ^6.1.2
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.5.0+1
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0


flutter_gen:
flutter:
  uses-material-design: true
  generate: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  